#!/bin/bash

array=("https://google.com" "https://facebook.com" "https://twitter.com")

log_file="website_status.log"

> $log_file

for i in "${array[@]}"; do

    http_status=$(curl -o /dev/null -s -w "%{http_code}" -L "$i")

    if [[ $http_status -eq 200 ]]; then
        echo "<$i> is UP" >> $log_file
    else
        echo "<$i> is DOWN" >> $log_file
    fi

done

echo "Results were written to $log_file"